src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @Assert\GreaterThanOrEqual("now")
     */
    private \DateTimeInterface $dateStart;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank()
     * @Assert\GreaterThan(propertyPath="dateStart")
     */
    private \DateTimeInterface $dateEnd;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private User $user;

    /**
     * @ORM\ManyToOne(targetEntity=Room::class, inversedBy="reservations")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     */
    private Room $room;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private string $code = '';

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $comment = null;

    /**
     * @ORM\Column(type="float")
     */
    private float $total = 0;

    /**
     * @ORM\Column(type="integer")
     */
    private int $status = 0;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateStart(): \DateTimeInterface
    {
        return $this->dateStart;
    }

    public function setDateStart(\DateTimeInterface $dateStart): self
    {
        $this->dateStart = $dateStart;

        return $this;
    }

    public function getDateEnd(): \DateTimeInterface
    {
        return $this->dateEnd;
    }

    public function setDateEnd(\DateTimeInterface $dateEnd): self
    {
        $this->dateEnd = $dateEnd;

        return $this;
    }

    public function getUser(): User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getRoom(): Room
    {
        return $this->room;
    }

    public function setRoom(Room $room): self
    {
        $this->room = $room;

        return $this;
    }

    public function getCode(): string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getTotal(): float
    {
        return $this->total;
    }

    public function setTotal(float $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getStatus(): int
    {
        return $this->status;
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getInvoice(): string
    {
        return 'invoices/facture-'.$this->id.'.pdf';
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"})
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private string $email = '';

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @ORM\Column(type="string")
     * @Assert\NotBlank()
     * @Assert\Regex(
     *     pattern="/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).{8,}$/",
     *     message="Votre mot de passe doit contenir au moins 8 caractères, 1 chiffre, 1 minuscule et 1 majuscule"
     * )
     */
    private string $password = '';

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private string $lastName = '';

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private string $firstName = '';

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $companyName = null;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Regex(
     *     pattern="/^(?:(?:\+|00)33[\s.-]{0,3}(?:\(0\)[\s.-]{0,3})?|0)[1-9](?:(?:[\s.-]?\d{2}){4}|\d{2}(?:[\s.-]?\d{3}){2})$/",
     *     message="Format du numéro de téléphone invalide",
     * )
     */
    private string $phone = '';

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\Luhn()
     */
    private ?int $siret = null;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private string $address = '';

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private string $zipCode = '';

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private string $city = '';

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $comment = null;

    /**
     * @ORM\Column(type="datetime")
     */
    private \DateTimeInterface $registerAt;

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="user", orphanRemoval=true)
     */
    private Collection $reservations;

    public function __construct()
    {
        $this->registerAt = new \DateTime();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        // A cause du RepeatedType dans RegistrationType
        $this->password = $password ?? '';

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastName(): string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFirstName(): string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->companyName;
    }

    public function setCompanyName(?string $companyName): self
    {
        $this->companyName = $companyName;

        return $this;
    }

    public function getPhone(): string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getSiret(): ?int
    {
        return $this->siret;
    }

    public function setSiret(?int $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getAddress(): string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZipCode(): string
    {
        return $this->zipCode;
    }

    public function setZipCode(string $zipCode): self
    {
        $this->zipCode = $zipCode;

        return $this;
    }

    public function getCity(): string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getRegisterAt(): ?\DateTimeInterface
    {
        return $this->registerAt;
    }

    public function setRegisterAt(\DateTimeInterface $registerAt): self
    {
        $this->registerAt = $registerAt;

        return $this;
    }

    public function getFullName(): string
    {
        return $this->firstName.' '.$this->lastName;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }
}

src/Form/Profile/EditPasswordType.php
<?php

namespace App\Form\Profile;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Validator\Constraints\UserPassword;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Regex;

class EditPasswordType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('currentPassword', PasswordType::class, [
                'label' => 'Mot de passe actuel',
                'constraints' => [
                    new UserPassword(),
                ],
                'attr' => [
                    'autocomplete' => 'off',
                ],
            ])
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'first_options' => [
                    'label' => 'Votre nouveau mot de passe *',
                    'help' => '8 caractères, 1 masjuscule, 1 minuscule, 1 chiffre',
                ],
                'second_options' => [
                    'label' => 'Confirmation du mot de passe',
                ],
                'constraints' => [
                    new NotBlank(),
                    new Regex([
                        'pattern' => '/^(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?!.*\s).{8,}$/',
                        'message' => 'Votre message doit contenir au moins 8 caractères, 1 chiffre, 1 minuscule et 1 majuscule.',
                    ]),
                ],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([]);
    }
}

src/Controller/ProfileController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Entity\User;
use App\Form\Profile\EditPasswordType;
use App\Form\Profile\ProfileType;
use App\Repository\ReservationRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface;

class ProfileController extends AbstractController
{
    /**
     * @Route("/mon-compte", name="profile_show")
     */
    public function show(): Response
    {
        return $this->render('profile/show.html.twig');
    }

    /**
     * @Route("/mon-compte/modifier", name="profile_edit")
     */
    public function edit(Request $request): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(ProfileType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'Votre compte a bien été modifié');

            return $this->redirectToRoute('profile_show');
        }

        return $this->renderForm('profile/edit.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route("/mon-compte/modifier-mot-de-passe", name="profile_edit_password")
     */
    public function editPassword(Request $request, UserPasswordHasherInterface $passwordHasher): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $form = $this->createForm(EditPasswordType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $password = $passwordHasher->hashPassword($user, $form->get('password')->getData());
            $user->setPassword($password);
            $this->getDoctrine()->getManager()->flush();
            $this->addFlash('success', 'Votre mot de passe a bien été modifié');

            return $this->redirectToRoute('profile_show');
        }

        return $this->renderForm('profile/edit_password.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route("/mon-compte/mes-reservations", name="profile_reservation")
     */
    public function showReservation(ReservationRepository $reservationRepository, PaginatorInterface $paginator, Request $request): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        $reservations = $paginator->paginate(
            $reservationRepository->showUserReservation($user),
            $request->query->getInt('page', 1),
            20
        );

        return $this->render('profile/show_reservation.html.twig', [
           'reservations' => $reservations,
        ]);
    }

    /**
     * @Route("/mon-compte/mes-reservations/{id}", name="profile_reservation_cancel", methods={"POST"})
     */
    public function cancelReservation(Request $request, Reservation $reservation): Response
    {
        $this->denyAccessUnlessGranted('RESERVATION_CANCEL', $reservation);

        if ($this->isCsrfTokenValid('cancel'.$reservation->getId(), (string) $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $reservation->setStatus(-1);
            $entityManager->flush();

            $this->addFlash('success', 'Votre réservation a bien été annulée');
        }

        return $this->redirectToRoute('profile_reservation', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/mon-compte/supprimer/{id}", name="profile_delete", methods={"POST"})
     */
    public function delete(Request $request, TokenStorageInterface $tokenStorage, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), (string) $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();

            $tokenStorage->setToken();
            $request->getSession()->invalidate();

            return $this->redirectToRoute('profile_account_deleted', [], Response::HTTP_SEE_OTHER);
        }

        $this->addFlash('danger', 'Erreur lors de la suppression du compte. Veuillez réessayer plus tard.');

        return $this->redirectToRoute('profile_show', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/compte-supprime", name="profile_account_deleted")
     */
    public function accountDeleted(): Response
    {
        return $this->render('profile/account_deleted.html.twig');
    }
}

templates/profile/account_deleted.html.twig
{% extends 'base.html.twig' %}

{% block title %}Votre compte a bien été supprimé{% endblock %}

{% block body %}
    <div class="container">
        <div class="py-5">
            <h1>Compte supprimé</h1>
            <p>Votre compte et ses données ont bien été supprimés.</p>
        <hr>
        <a href="{{ path('site_index') }}" class="btn btn-dark"> Retourner à l'accueil</a>
        </div>
    </div>
{% endblock %}

templates/profile/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier mon compte{% endblock %}

{% block body %}
    <div class="container">
        <div class="py-5">
            <h1 class="mb-4">Modifier mon compte</h1>
            {{ form_start(form) }}
                {{ form_widget(form) }}
                <button class="btn btn-orange">{{ button_label|default('Modifier') }}</button>
            {{ form_end(form) }}
        <hr class="mt-5">
        <a href="{{ path('profile_show') }}" class="btn btn-dark"> Retourner au compte</a>
        </div>
    </div>
{% endblock %}

templates/profile/edit_password.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier mon mot de passe{% endblock %}

{% block body %}
    <div class="container">
        <div class="py-5">
            <h1>Modifier mon mot de passe</h1>

            {{ form_start(form) }}
                {{ form_widget(form) }}
                <button class="btn btn-orange">{{ button_label|default('Modifier') }}</button>
            {{ form_end(form) }}
        <hr class="mt-5">
        <a href="{{ path('profile_show') }}" class="btn btn-dark"> Retourner au compte</a>
        </div>
    </div>
{% endblock %}

templates/profile/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon compte{% endblock %}

{% block body %}
    <div class="container">
        <div class="py-5 flex">
            <h1 class="mb-4">Mon compte</h1>
            {% include 'utils/alert.html.twig' %}
            <h3>{{ app.user.fullName }} <small class="text-muted">#{{ app.user.id }}</small></h3>
            <ul>
                <li><strong>Email</strong> : {{ app.user.email }}</li>
                <li><strong>Téléphone</strong> : {{ app.user.phone }}</li>
                <li><strong>Adresse</strong> : {{ app.user.address }} - {{ app.user.zipCode }} {{ app.user.city }}</li>
                <li><strong>Date d'inscription</strong> : {{ app.user.registerAt|date('d-m-Y H:i:s') }}</li>
            </ul>

            {% if app.user.companyName is not empty %}
                <h3>Entreprise : {{ app.user.companyName }}</h3>
                <p>Siret: {{ app.user.siret ? app.user.siret : 'N/C' }}</p>
            {% endif %}
            <hr class="mt-5">
            <div class="d-flex">
            <a href="{{ path('profile_edit') }}" class=" btn btn-orange me-2">Modifier mon compte</a>
            <a href="{{ path('profile_edit_password') }}" class=" btn btn-secondary me-2">Modifier mon mot de passe</a>
            <form method="post" action="{{ path('profile_delete', {'id': app.user.id}) }}" onsubmit="return confirm('Voulez-vous vraiment supprimer votre compte?');">
                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ app.user.id) }}">
                <button class="btn btn-danger">Supprimer mon compte</button>
            </form>
        </div>
    </div>
{% endblock %}

templates/profile/show_reservation.html.twig
{% extends "base.html.twig" %}

{% block title %}Mes réservations{% endblock %}

{% block body %}
    <div class="py-5">
        <div class="container">
            <h1>Mes réservations</h1>

            {% include 'utils/alert.html.twig' %}

            <table class="table">
                <thead>
                    <tr>
                        <th>Début</th>
                        <th>Fin</th>
                        <th>Salle</th>
                        <th>Code</th>
                        <th>Statut</th>
                        <th>Prix</th>
                        <th>Actions</th>
                    </tr>
                </thead>

                <tbody>
                    {% for reservation in reservations %}
                        <tr>
                            <td>{{ reservation.dateStart|date('d-m-Y H:i') }}</td>
                            <td>{{ reservation.dateEnd|date('d-m-Y H:i') }}</td>
                            <td>{{ reservation.room.name }}</td>
                            <td>{{ reservation.code }}</td>
                            <td>{% include 'utils/_reservation_status_badge.html.twig' %}</td>
                            <td>{{ reservation.total|number_format(2, ',', ' ') }}€</td>
                            <td class="d-flex">
                                <a href="{{ asset(reservation.invoice) }}" target="_blank" class="btn btn-link" data-bs-toggle="tooltip" data-bs-placement="top" title="Télécharger la facture"><i class="bi bi-file-earmark-arrow-down fs-5"></i></a>
                                {% if is_granted('RESERVATION_CANCEL', reservation) %}
                                    <form method="post" action="{{ path('profile_reservation_cancel', {'id': reservation.id}) }}" onsubmit="return confirm('Voulez-vous vraiment annuler cette réservatio?');">
                                        <input type="hidden" name="_token" value="{{ csrf_token('cancel' ~ reservation.id) }}">
                                        <button class="btn btn-link" name="cancel" data-bs-toggle="tooltip" data-bs-placement="top" title="Annuler la réservation"><i class="bi bi-x-square fs-5"></i></button>
                                    </form>
                                {% endif %}
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="7">Aucune réservation</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <div class="d-flex justify-content-center">
                {{ knp_pagination_render(reservations) }}
            </div>
        </div>
    </div>
{% endblock %}